runtime: java17
instance_class: F1
entrypoint: java -jar target/transport-0.0.1-SNAPSHOT.jar

env_variables:
  SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
  SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
  SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
